import Head from 'next/head'
import Footer from './Footer'
import Header from './Header'

const Layout = ({ children, page, guitarra, carrito }) => {

    return (
        <div>
            <Head>
                <title>Guitar LA - {page}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header guitarra={guitarra} carrito={carrito} />
            {children}
            <Footer />
        </div>
    )
}

Layout.defaulprops = {
    guitarra: null
} 

export default Layout